version: "3.7"
services:
  flight-booking-system:
    #build: .
    image: flight-booking-system:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - flightbook
  flightbook:
    image: "mongo:6.0.1"
    restart: always
    ports:
      - 27017:27017